# Generated by Django 3.1.5 on 2026-03-15 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0005_moduleaccess_database'),
        ('hr2', '0002_auto_20241020_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePerYear',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('casual_leave', models.IntegerField(default=8)),
                ('restricted_holiday', models.IntegerField(default=2)),
                ('earned_leave', models.IntegerField(default=15)),
                ('vacation_leave', models.IntegerField(default=60)),
                ('commuted_leave', models.IntegerField(default=20)),
                ('special_casual_leave', models.IntegerField(default=15)),
                ('year', models.IntegerField(default=2026)),
            ],
        ),
        migrations.RemoveField(
            model_name='ltcform',
            name='phoneNumberForContact',
        ),
        migrations.AddField(
            model_name='appraisalform',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FORWARDED', 'Forwarded'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='cpdaadvanceform',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FORWARDED', 'Forwarded'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='cpdareimbursementform',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FORWARDED', 'Forwarded'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('FACULTY', 'Faculty'), ('STAFF', 'Staff')], default='FACULTY', max_length=20),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='Hr2/leave_forms/'),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FORWARDED', 'Forwarded'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='ltcform',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FORWARDED', 'Forwarded'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='empconfidentialdetails',
            name='bank_account_no',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='empdependents',
            name='extra_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.extrainfo'),
        ),
        migrations.CreateModel(
            name='LeaveClaim',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('days_taken', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leaveForm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr2.leaveform')),
            ],
        ),
    ]
